// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUkDqJebwuE09AzaFgJTiyXUrKdqyaDY',
    appId: '1:523725204694:web:d6df20b9a88de8d8d26d77',
    messagingSenderId: '523725204694',
    projectId: 'googolesign',
    authDomain: 'googolesign.firebaseapp.com',
    storageBucket: 'googolesign.firebasestorage.app',
    measurementId: 'G-S0EZNZ4EH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0_VeO22XFOI-OOSzNWvP9jzuZxpOLmI',
    appId: '1:523725204694:android:21b2f5d3cb0e1cdfd26d77',
    messagingSenderId: '523725204694',
    projectId: 'googolesign',
    storageBucket: 'googolesign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmqeLbp-ZDbIKeQFVbL7vFXfFIAbWV20',
    appId: '1:523725204694:ios:95900fba60358ca4d26d77',
    messagingSenderId: '523725204694',
    projectId: 'googolesign',
    storageBucket: 'googolesign.firebasestorage.app',
    iosBundleId: 'com.example.firegoogleservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmqeLbp-ZDbIKeQFVbL7vFXfFIAbWV20',
    appId: '1:523725204694:ios:95900fba60358ca4d26d77',
    messagingSenderId: '523725204694',
    projectId: 'googolesign',
    storageBucket: 'googolesign.firebasestorage.app',
    iosBundleId: 'com.example.firegoogleservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhUkDqJebwuE09AzaFgJTiyXUrKdqyaDY',
    appId: '1:523725204694:web:083ea1d898a7785cd26d77',
    messagingSenderId: '523725204694',
    projectId: 'googolesign',
    authDomain: 'googolesign.firebaseapp.com',
    storageBucket: 'googolesign.firebasestorage.app',
    measurementId: 'G-BG5FZCNXR1',
  );
}
